"""dnc and campaign_tasks

Revision ID: 1d6479413c0b
Revises: e75aa6b272c5
Create Date: 2026-08-24 16:43:54.903607
"""
from alembic import op
import sqlalchemy as sa


revision = '1d6479413c0b'
down_revision = 'e75aa6b272c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_at', sa.DateTime(), nullable=False),
    sa.Column('provider_call_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_tasks_campaign_id'), 'campaign_tasks', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_tasks_lead_id'), 'campaign_tasks', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_tasks_next_at'), 'campaign_tasks', ['next_at'], unique=False)
    op.create_index(op.f('ix_campaign_tasks_org_id'), 'campaign_tasks', ['org_id'], unique=False)
    op.create_table('do_not_call',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_index(op.f('ix_do_not_call_org_id'), 'do_not_call', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_do_not_call_org_id'), table_name='do_not_call')
    op.drop_table('do_not_call')
    op.drop_index(op.f('ix_campaign_tasks_org_id'), table_name='campaign_tasks')
    op.drop_index(op.f('ix_campaign_tasks_next_at'), table_name='campaign_tasks')
    op.drop_index(op.f('ix_campaign_tasks_lead_id'), table_name='campaign_tasks')
    op.drop_index(op.f('ix_campaign_tasks_campaign_id'), table_name='campaign_tasks')
    op.drop_table('campaign_tasks')
    # ### end Alembic commands ###
