"""call_states table

Revision ID: e75aa6b272c5
Revises: 89d8625ad030
Create Date: 2026-08-18 13:02:41.504058
"""
from alembic import op
import sqlalchemy as sa


revision = 'e75aa6b272c5'
down_revision = '89d8625ad030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_states',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_call_states_lead_id'), 'call_states', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_states_lead_id'), table_name='call_states')
    op.drop_table('call_states')
    # ### end Alembic commands ###
